-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.transactions
(
    id serial NOT NULL,
    date date NOT NULL,
    amount numeric(6,2) NOT NULL,
    description text[] NOT NULL,
    type_id integer,
    company_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transaction_type
(
    id serial NOT NULL,
    type_name text[] NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.company
(
    id serial NOT NULL,
    company_name text[],
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.transactions
    ADD FOREIGN KEY (type_id)
    REFERENCES public.transaction_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transactions
    ADD FOREIGN KEY (company_id)
    REFERENCES public.company (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;