-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.company
(
    company_id BIGSERIAL NOT NULL,
    company_name character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT company_pkey PRIMARY KEY (company_id)
);

CREATE TABLE IF NOT EXISTS public.transaction_type
(
    transaction_type_id BIGSERIAL NOT NULL,
    type_name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT transaction_type_pkey PRIMARY KEY (transaction_type_id)
);

CREATE TABLE IF NOT EXISTS public.transactions
(
    transaction_id BIGSERIAL NOT NULL,
    date date NOT NULL,
    amount numeric(6, 2) NOT NULL,
    type_id integer,
    company_id integer,
    description character varying(400) COLLATE pg_catalog."default",
    CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id)
);

ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT transactions_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES public.company (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT transactions_type_id_fkey FOREIGN KEY (type_id)
    REFERENCES public.transaction_type (transaction_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;